### PR TITLE
Patch for Drupal 9

### PR DESCRIPTION
**Pull request by saschaeggi**
Patched the deprecated functions to make it work with Drupal 9

### CODE REVIEW

**Comment by leymannx** [comment]
Shouldn't the core key be left there to also make it work with older Drupal versions? Thought it might only be removed when you have the core_version_requirement to ^8.8 || ^9. https://www.drupal.org/node/3070687

**Comment by saschaeggi** [comment]
That's right, that was my fault. It's updated now. Thanks!

**Comment by newtimber** [comment]
This gives an error message when clearing the cache:-

Error: Non-static method Drupal\Core\Messenger\MessengerInterface::addMessage() cannot be called statically in Drupal\lite_speed_cache\Form\LSCacheForm->submitThisCache()

**Comment by leymannx** [comment]
Ah yeah, right it must be `\Drupal::messenger()->addMessage($message);` at this point.

**Comment by Woet** [comment]
Thank you for this! I'll push a commit with the MessengerInterface fix shortly.

**Pull request merged**
